# Copyright (c) 2017 Board of Trustees University of Illinois
---
# can't use reboot module on localhost
# https://github.com/ansible/ansible/issues/57874
- name: reboot
  shell: sleep 2 && reboot
  async: "{{ reboot_timeout | default(300) }}"
  poll: 0 # fire and forget
  register: reboot_flag
  # async always fails in check mode
  ignore_errors: "{{ ansible_check_mode }}"

- name: rndc reconfig
  command: /usr/sbin/rndc reconfig
  when: reboot_flag is undefined

- name: restart named
  service:
    name: named
    state: restarted
  when: reboot_flag is undefined
